export const GET_USER_DISCOUNTS = 'GET_USER_DISCOUNTS';
export const GET_USER_DISCOUNTS_SUCCESS = 'GET_USER_DISCOUNTS_SUCCESS';
export const GET_USER_DISCOUNTS_ERROR = 'GET_USER_DISCOUNTS_ERROR';

export const SAVE_USER_DISCOUNTS = 'SAVE_USER_DISCOUNTS';
export const SAVE_USER_DISCOUNTS_SUCCESS = 'SAVE_USER_DISCOUNTS_SUCCESS';
export const SAVE_USER_DISCOUNTS_ERROR = 'SAVE_USER_DISCOUNTS_ERROR';